version: "3.8"

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=vilaw_db
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads
      - ./.env:/app/.env
    networks:
      - vilaw-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=vilaw_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vilaw-network

volumes:
  postgres_data:

networks:
  vilaw-network:
    driver: bridge
